### ISSUE TITLE
logfiler fra biblo

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#647]
Strukturen på biblo's logfiler giver fejl.

EN opgradering/omlægning af miljø'et er undervejs og derfor ser man gerne Biblo's logstruktur bliver kigget på og rettet til.

@hrmoller:
Efter snak med/feedback fra @vibjerg og @KiraH laves følgende:
- [x] Opdater Biblo til at benytte dbc-node-logger version 2.x.x
- [x] Express loggers
- [x] Det skal sikres at de af Biblo’s afhængigheder, der bruger dbc-node-logger ligeledes er kompatible med version 2.x.x.
- [x] Det skal sikres at `data`-key’en altid indeholder en streng (JSON.stringify) (https://github.com/DBCDK/dbc-node-logger/issues/6)
- [x] Det skal sikres at `timing` altid er et tal (https://github.com/DBCDK/dbc-node-logger/issues/6)
- [x] Der skal muligvis laves en ny release af dbc-node-logger (https://github.com/DBCDK/dbc-node-logger/issues/6)
- [x] ~Omdøb request til params I dbc-node-serviceprovider~ (https://github.com/DBCDK/dbc-node-serviceprovider/issues/19)
- [x] Kopier kode fra DBCDK/dbc-node-serviceprovider til Biblo

**Comment by BettinaAndersen** [comment]
Krav:
-	Nuværende logning skal kortlægges.
-	Logning skal ændres, så denne er konsistent og i overensstemmelse med ITs-retningslinjer.
-	Biblo skal logge til standard-out i stedet for Kafka.
